version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      - mysql-net
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_LOG_CONSOLE=true

  prestashop_1.7.4:
    image: prestashop/prestashop:1.7.4.2
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - "prestashop:/var/www/"
    networks:
      - mysql-net
    environment:
      - DB_SERVER=mysql
      - DB_PREFIX=ps174_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8083
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed

volumes:
  db_data:
    driver: local
  prestashop:
    driver: local

networks:
  mysql-net:
    # swarm
    # driver: overlay